common:
  cluster: cluster1
glooAgent:
  enabled: true
  runAsSidecar: true
  image:
    registry: harbor-preprod.blackrock.com/library/external/gcr.io/gloo-mesh
  relay:
    serverAddress: gloo-mesh-mgmt-server.cnp-nginx:9900
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
glooAnalyzer:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
glooMgmtServer:
  enabled: true
  registerCluster: true
  policyApis:
    enabled: true
  image:
    registry: harbor-preprod.blackrock.com/library/external/gcr.io/gloo-mesh
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi
  serviceOverrides:
    metadata:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true" 
glooInsightsEngine:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
glooUi:
  enabled: true
  image:
    registry: harbor-preprod.blackrock.com/library/external/gcr.io/gloo-mesh
  sidecars:
    console:
      image:
        registry: harbor-preprod.blackrock.com/library/external/gcr.io/gloo-mesh
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 250m
          memory: 256Mi
    envoy:
      image:
        registry: harbor-preprod.blackrock.com/library/external/gcr.io/gloo-mesh
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
  # serviceType: LoadBalancer
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
prometheus:
  enabled: true
  server:
    image:
      repository: harbor-preprod.blackrock.com/library/external/gcr.io/gloo-mesh/prometheus
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
  configmapReload:
    prometheus:
      image:
        repository: harbor-preprod.blackrock.com/library/external/quay.io/prometheus-operator/prometheus-config-reloader
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
redis:
  deployment:
    enabled: true
    image:
      registry: harbor-preprod.blackrock.com/library/external/gcr.io/gloo-mesh
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
# jaeger:
#   enabled: true
telemetryCollector:
  enabled: true
  image:
    repository: harbor-preprod.blackrock.com/library/external/gcr.io/gloo-mesh/otel-collector
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
telemetryGateway:
  enabled: true
  image:
    repository: harbor-preprod.blackrock.com/library/external/gcr.io/gloo-mesh/otel-collector
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true" 
telemetryGatewayCustomization:
  pipelines:
    traces/jaeger:
      enabled: true
telemetryCollectorCustomization:
  pipelines:
    traces/istio:
      enabled: true
installEnterpriseCrds: false
featureGates:
  ConfigDistribution: false

